# docker-compose.yml

version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: gunicorn backend.asgi:application --bind 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker --workers 4
    volumes:
      - static_volume:/code/static
      - ./nginx/:/code/nginx/:rw
      - ./scripts/:/code/scripts/:rw
      - ./backend/backend/tenants_db/:/code/backend/tenants_db/:rw
    expose:
      - 8000
    depends_on:
      - db
    environment:
      - DB_NAME=tenants
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  nginx:
#    image: nginx:latest
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - static_volume:/code/static
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - web

  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tenants
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db


volumes:
  static_volume:
  postgres_data:
